CREATE DATABASE IF NOT EXISTS cloudnova CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cloudnova;
CREATE TABLE admins(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,email VARCHAR(255) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE enquiries(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150) NOT NULL,email VARCHAR(255) NOT NULL,phone VARCHAR(40),company VARCHAR(150),message TEXT NOT NULL,status ENUM('new','contacted','closed') DEFAULT 'new',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE services(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(150) NOT NULL,description TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE plans(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,price VARCHAR(50) NOT NULL,period VARCHAR(50),features TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE faq(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,question VARCHAR(255) NOT NULL,answer TEXT NOT NULL);
-- Generate a password hash with PHP password_hash() and insert it here.
-- Example: INSERT INTO admins(email,password_hash) VALUES('admin@example.com','PASTE_HASH_HERE');
